FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r requirements.txt

COPY shared/ ${LAMBDA_TASK_ROOT}/shared/
COPY lambdas/zcta_handler.py ${LAMBDA_TASK_ROOT}/

CMD ["zcta_handler.handler"]
